[package]
name        = "odin"
version     = "0.0.0"
description = "ğŸ‘ï¸ Relentless seeker of knowledge"
license     = "CC0-1.0"
homepage    = "https://github.com/casey/odin"
authors     = ["Casey Rodarmor <casey@rodarmor.com>"]
edition     = "2018"

[dependencies]
ansi_term    = "0.12.0"
atty         = "0.2.13"
indoc        = "0.3.3"
itertools    = "0.8.0"
libc         = "0.2.62"
serde        = "1.0.97"
serde_derive = "1.0.97"
serde_json   = "1.0.40"
serde_yaml   = "0.8.9"
structopt    = "0.2.18"
tera         = "1.0.0-beta.14"
textwrap     = "0.11.0"
url          = "2.1.0"
webbrowser   = "0.5.1"
xdg          = "2.2.0"

[dev-dependencies]
executable-path = "1.0.0"
tempfile        = "3.1.0"
unindent        = "0.1.3"
